"""Deterministic fake engine.

Exists so the whole pipeline — ingest, windowing, prompting, scoring, export — can be
exercised and demoed before a multi-gigabyte download finishes. It never looks at the
pixels, and every response says so.
"""

from __future__ import annotations

import time
from typing import Iterator

from .base import Engine, GenerationRequest

_REPORT = """\
[MOCK ENGINE — bu haqiqiy model javobi EMAS / this is NOT real model output]

FINDINGS:
The lungs are clear without focal consolidation, pleural effusion, or pneumothorax.
The cardiomediastinal silhouette is within normal limits. The visualized osseous
structures are intact. No acute abnormality is identified.

IMPRESSION:
1. No acute cardiopulmonary abnormality.

---
This text is generated by the built-in mock backend to verify the DICOM pipeline,
prompt assembly, streaming, and scoring UI. Switch the engine to `transformers`
to get real model output.
"""

_JSON = """\
{"verdict": "abnormal", "confidence": 0.0, "key_finding": "MOCK ENGINE - not real output",
 "reasoning": "The mock backend does not inspect pixel data. Switch to a real engine."}
"""


class MockEngine(Engine):
    key = "mock"
    label = "Mock (model yo'q / no model)"
    requires_network = False
    default_model = "mock-medgemma"

    @classmethod
    def check_available(cls) -> tuple[bool, str]:
        return True, "Always available; produces placeholder text only."

    def device_name(self) -> str:
        return "cpu"

    def stream(self, req: GenerationRequest) -> Iterator[str]:
        body = _JSON if '"verdict"' in req.user_text or "strict JSON" in req.user_text else _REPORT
        header = f"[mock: {len(req.images)} image(s) received]\n\n"
        for token in (header + body).split(" "):
            time.sleep(0.012)
            yield token + " "
